feat: read lyrics from ID3v2 tag
linuxdeepin/deepin-music pull request #111
Opened 2022-01-15 10:51 UTC by kt286

read lyrics from  ID3v2 tag when the *.lrc file not found in media file root dir

2022-01-15 10:51 UTC, Sunnshino commented
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

2022-01-17 05:53 UTC, iamhyc commented
@babyfengfjx @Sunnshino Could someone kindly help review this PR?

 It seems like the maintainer "Wang Yu" is not on Github.

2022-01-18 08:45 UTC, wythe0701 reviewed
The 'byteArray' is not used, it is recommended to delete it

2022-01-18 10:37 UTC, kt286 commented
> The 'byteArray' is not used, it is recommended to delete it

modified

2022-01-24 08:12 UTC, kt286 commented
@wangyu0701 test music: https://github.com/linuxdeepin/deepin-music/files/7923703/-.Lao.zip

2022-03-10 08:26 UTC, lzwind commented
This is a new function. We are evaluating it. It will take some time. Please wait patiently. Thank you!

2022-07-13 05:27 UTC, zccrs requested changes

2022-07-13 05:27 UTC, zccrs commented on src/music-player/presenter/dboperate.cpp
> +        QFileInfo lyricInfo(Global::cacheDir() + "/lyrics/" + meta.hash + ".lrc");
这个路径的组合我看不止这一个地方在用，建议封装成一个 inline static 的功能函数，在用到的地方换成函数调用，避免以后有相关逻辑需要改动的时候可能漏掉了改另外相同的地方。

2022-07-13 05:27 UTC, zccrs commented on src/music-player/widget/lrc/musiclyricwidget.cpp
> +            m_lyricview->hide();
最好是先hide再show另一个，虽然实际感官上看不出区别，不过逻辑上这样会更合适

2022-07-19 12:50 UTC, kt286 commented on src/music-player/presenter/dboperate.cpp
> +        QFileInfo lyricInfo(Global::cacheDir() + "/lyrics/" + meta.hash + ".lrc");
分散在3个文件。不知道该定义到哪里

2023-12-01 06:03 UTC, closed without merging